info:
  title: Demo of WoT Interface Creation
  version: 1.0.0
openapi: 3.0.0
paths:
  /humidity/1:
    get:
      operationId: get_humidity_grove
      responses:
        '200':
          description: OK
      summary: get_humidity_grove request on device grove_temperature_humidity_sensor
  /temperature/1:
    get:
      operationId: get_temperature_grove
      responses:
        '200':
          description: OK
      summary: get_temperature_grove request on device grove_temperature_humidity_sensor
servers:
- url: https://192.168.178.22:9000/api
- url: coap://192.168.178.22
